name: CI
on:
  push: 
    branches: [main,master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
      - name: install deps
        run: npm ci
      - name: build app
        run: npm run build --if-present
      - name: enter the dist directory
        run: cd dist
      - name: git init
        run: git init
      - name: git config
        run: git checkout -b master
      - name: git add
        run: git add -A
      - name: git commit
        run: git commit -m 'deploy'
      - name: git push
        run: git push -f git@github.com:mycInk/kanban-for-end.git main:gh-pages
      - name: cd back
        run: cd -
